// <auto-generated />
using System;
using Finances.Valuation.Application.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Finances.Valuation.Application.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fin")
                .HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Finances.Valuation.Application.Features.Debts.Models.Debt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("DebtType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Interest")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Payment")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SavingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SavingId");

                    b.ToTable("debts", "fin");
                });

            modelBuilder.Entity("Finances.Valuation.Application.Features.Incomes.Models.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("incomes", "fin");
                });

            modelBuilder.Entity("Finances.Valuation.Application.Features.Investments.Models.Investment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("investments", "fin");
                });

            modelBuilder.Entity("Finances.Valuation.Application.Features.Savings.Models.Saving", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExpectedMonthlyContributionAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("savings", "fin");
                });

            modelBuilder.Entity("Finances.Valuation.Application.Features.Spendings.Models.Spending", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("spendings", "fin");
                });

            modelBuilder.Entity("Finances.Valuation.Application.Features.Strategies.Models.Strategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("strategies", "fin");
                });

            modelBuilder.Entity("Finances.Valuation.Application.Features.Strategies.Models.StrategyConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DebtId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InvestmentId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MonthlyContributionAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MonthlyContributionPercentage")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SavingId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpendingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StrategyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DebtId");

                    b.HasIndex("InvestmentId");

                    b.HasIndex("SavingId");

                    b.HasIndex("SpendingId");

                    b.ToTable("strategies_configurations", "fin");
                });

            modelBuilder.Entity("Finances.Valuation.Application.Features.Debts.Models.Debt", b =>
                {
                    b.HasOne("Finances.Valuation.Application.Features.Savings.Models.Saving", "Saving")
                        .WithMany()
                        .HasForeignKey("SavingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Saving");
                });

            modelBuilder.Entity("Finances.Valuation.Application.Features.Strategies.Models.StrategyConfiguration", b =>
                {
                    b.HasOne("Finances.Valuation.Application.Features.Debts.Models.Debt", "Debt")
                        .WithMany()
                        .HasForeignKey("DebtId");

                    b.HasOne("Finances.Valuation.Application.Features.Investments.Models.Investment", "Investment")
                        .WithMany()
                        .HasForeignKey("InvestmentId");

                    b.HasOne("Finances.Valuation.Application.Features.Savings.Models.Saving", "Saving")
                        .WithMany()
                        .HasForeignKey("SavingId");

                    b.HasOne("Finances.Valuation.Application.Features.Spendings.Models.Spending", "Spending")
                        .WithMany()
                        .HasForeignKey("SpendingId");

                    b.Navigation("Debt");

                    b.Navigation("Investment");

                    b.Navigation("Saving");

                    b.Navigation("Spending");
                });
#pragma warning restore 612, 618
        }
    }
}
