name: Publish

on: 
  workflow_dispatch:
  push:
    branches:
      - main
env: 
  AZURE_WEBAPP_NAME: finance-valuation
  AZURE_WEBAPP_PACKAGE_PATH: "./src/Finances.Valuation.Application/publish"
  DOTNET_VERSION: "9.x"
  SOLUTION_PATH: "finance-valuation.sln"
  API_PROJECT_PATH: "./src/Finances.Valuation.Application"
  PUBLISH_DIR: "./publish"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install React dependencies
        run: npm ci
        working-directory: ./src/finance-valuation-client 

      - name: Build React app
        run: npm run build
        working-directory: ./src/finance-valuation-client 

      - name: Copy React build to wwwroot
        run: |
          rm -rf ./src/Finances.Valuation.Application/wwwroot/*
          cp -r ./src/finance-valuation-client/dist/* ./src/Finances.Valuation.Application/wwwroot/
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}
      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore
      - name: Publish
        run: dotnet publish ${{ env.API_PROJECT_PATH }} --configuration Release --no-restore --no-build --property:PublishDir=${{ env.PUBLISH_DIR }}
      - name: List publish folder
        run: ls -la ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: List publish folder wwwroot
        run: ls -la ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/wwwroot

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  deploy:
      name: Deploy to Azure
      runs-on: ubuntu-latest
      needs: [build]

      steps:
         - name: Download artifact from build job
           uses: actions/download-artifact@v5
           with: 
             name: webapp
             path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
         - name: Deploy 
           uses: Azure/webapps-deploy@v2
           with:
              app-name: ${{ env.AZURE_WEBAPP_NAME }}
              publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
              package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          

      
